// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtkCmNV8h60n3SJCeZ1Zjjhwkq17YwLWg',
    appId: '1:4007434575:web:a4783162734b3f42ce0d3a',
    messagingSenderId: '4007434575',
    projectId: 'arboreal-lane-509612-q9',
    authDomain: 'arboreal-lane-509612-q9.firebaseapp.com',
    storageBucket: 'arboreal-lane-509612-q9.firebasestorage.app',
    measurementId: 'G-8T6G1KCPFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpVLHP54R1T7yXnDZFy7UZwes5Aoli4Gw',
    appId: '1:4007434575:android:e540af73f28c6759ce0d3a',
    messagingSenderId: '4007434575',
    projectId: 'arboreal-lane-509612-q9',
    storageBucket: 'arboreal-lane-509612-q9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmpQbGTw1gkhhdC9KtZW-TwX5TGZUBKrY',
    appId: '1:4007434575:ios:ccbae15f6b2361c7ce0d3a',
    messagingSenderId: '4007434575',
    projectId: 'arboreal-lane-509612-q9',
    storageBucket: 'arboreal-lane-509612-q9.firebasestorage.app',
    iosBundleId: 'com.example.recipeKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmpQbGTw1gkhhdC9KtZW-TwX5TGZUBKrY',
    appId: '1:4007434575:ios:ccbae15f6b2361c7ce0d3a',
    messagingSenderId: '4007434575',
    projectId: 'arboreal-lane-509612-q9',
    storageBucket: 'arboreal-lane-509612-q9.firebasestorage.app',
    iosBundleId: 'com.example.recipeKeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtkCmNV8h60n3SJCeZ1Zjjhwkq17YwLWg',
    appId: '1:4007434575:web:0057a0aeabfca7fbce0d3a',
    messagingSenderId: '4007434575',
    projectId: 'arboreal-lane-509612-q9',
    authDomain: 'arboreal-lane-509612-q9.firebaseapp.com',
    storageBucket: 'arboreal-lane-509612-q9.firebasestorage.app',
    measurementId: 'G-3WKWWPVTS2',
  );
}
